name: Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron : 30 02 * * * #8:00 AM IST EveryDay
    - cron : 00 14 * * * #7:30 PM IST EveryDay
    - cron : 00 06 * * 1-5 #11:30 AM IST Monday-Friday

jobs:
  run-postman_tests:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout the code
        uses: actions/checkout@v4.2.2

      - name: Install Nodejs and npm
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '22'

      - name: Install Newman and Newman-html-extra
        run:  |
              npm install -g newman
              npm install -g newman-reporter-htmlextra

      - name: Run the Postman Collection with Newman
        run:  |
              newman run 'Inwarranty-flow Collection.postman_collection with External Data API.json' \
              -e QA.postman_environment.json \
              -d testdata.csv \
              -r cli,htmlextra
              
              

              
        
    
